globalbrain/sefirot

lib/components/inputs/SInputRadio.vue
Issue #1
This PR fixes InputRadio circle to be aligned at center in different zoom level.
=> #1 Fix input radio circle align center at different zoom level

docs/components/stories/placeholders/ExamplePlaceholderBlankPositions.vue, docs/components/stories/placeholders/ShowcasePlaceholderBlank.vue, docs/pages/components/placeholders-blank/index.vue, lib/components/placeholders/SPlaceholderBlank.vue
Issue #3 
This PR adds positioning option to SPlaceholderBlank component.
=> #3 Add positioning control feature to SPlaceholderBlank

docs/assets/styles/reboot.css, docs/components/stories/inputs/ShowcaseSelect.vue, docs/pages/components.vue, docs/pages/components/inputs-select/index.vue, lib/assets/styles/reboot.css, lib/components/inputs/SInputSelect.vue, test/components/inputs/SInputSelect.spec.js
Issue #6 
This PR adds select input component, `SInputSelect`.
=> #6 Add select input component

docs/components/stories/buttons/ExampleRoundedButton.vue, docs/pages/components/buttons/index.vue, lib/components/buttons/SButton.vue
Issue #8
This PR adds rounded style to the button component.
=> #8 Add rounded style to the button component

docs/pages/components/grids/index.vue, lib/components/grids/SGrid.vue
This PR adds ability to pass `style` option to the SGrid component.
=> Add style option to the SGrid component

.babelrc, lib/components/SButton.vue, package.json, yarn.lock
=> fix: button block property not working as expected (#16)

docs/components/StoryButtonEXJumbo.vue, docs/pages/components/buttons/index.vue, lib/components/SButton.vue
=> feat: add jumbo size to the button component (#17)

docs/assets/styles/components/c-medium.css, docs/assets/styles/variables.css, docs/components/StoryInputSelectShowcase.vue, lib/components/SInputSelect.vue, package.json, test/components/SInputSelect.spec.ts, yarn.lock
fix #20
This PR fixes style issue for the SInputSelect component.
=> fix: input select component style (#20)

lib/components/SInputSelect.vue, lib/components/SPortalModals.vue
=> fix: body scrolls to top when switching open modals (#21)

docs/assets/styles/base.css, docs/components/StoryInputTextareaEXClear.vue, docs/pages/components/inputs-textarea/index.vue, lib/assets/styles/base.css, lib/components/SInputTextarea.vue, test/components/SInputTextarea.spec.ts
fix #26 
This PR fixes where textarea component is missing its error border style.
=> fix: textarea component missing error border style (#26)

lib/validation/rules/index.ts, lib/validation/rules/maxLength.ts, lib/validation/validators/index.ts, lib/validation/validators/maxLength.ts, test/validation/validators/maxLength.spec.ts
close #34
Add max length validation.
=> feat(validation): implement max length validation (#34)

docs/pages/components/inputs-switch/index.vue, lib/components/SAction.vue, lib/components/SActionSwitch.vue, lib/components/SInputSwitch.vue, lib/composables/Action.ts, lib/composables/Utils.ts
Implement following things.
- Add `SActionSwitch` component.
- Add `textMode` props to SInputSwitch to change the color of "text".
- Add `computedArrayIfNot()` in util.
=> add SActionSwitch component

test/components/SInputDropdown.spec.ts
Add `input-dropdown` spec since it's a documented component.
=> test: add input-dropdown spec

lib/composables/Alert.ts
=> feat(alert): improve composition

lib/components/SInputDate.vue
Add missing props `placeholder` to `SInputDate`.
=> fix: add missing placeholer props to SInputDate

docs/components/steps/StoryStepsEXWithoutText.vue, docs/components/steps/StoryStepsShowcase.vue, docs/pages/components.vue, docs/pages/components/steps/index.vue, lib/components/SStep.vue, lib/components/SSteps.vue, lib/composables/Step.ts, test/components/SSteps.spec.ts
This PR adds a new steps component that displays a steps in a flow.
=> feat(step): add SSteps component

lib/components/SAlert.vue, lib/components/SCard.vue, lib/components/SCardFooter.vue, lib/components/SCardHeader.vue, lib/components/SInputBase.vue, lib/composables/Alert.ts, lib/composables/Card.ts, lib/composables/Utils.ts
=> feat: refactor bunch of stuff

lib/components/SMarkdown.vue, lib/composables/Markdown.ts, package.json, test/components/SMarkdown.spec.ts, test/composables/Markdown.spec.ts, yarn.lock
=> refactor(markdown): replace `selector` with container `ref`

lib/components/SPortalModals.vue, lib/composables/Alert.ts, lib/composables/Dialog.ts, lib/composables/Modal.ts
resolves #74 
Additionally, modal compositions return store actions for awaitable procedures.
=> fix(modal): handle active state timer (#74)

lib/components/SInputYear.vue
close https://github.com/globalbrain/sefirot/issues/79
Emit number value only when the value can be converted to a number that is not NaN.
=> fix: emit number only when value is not NaN (#79) 

lib/components/SCardHeader.vue
Make the disabled button not clickable.
=> fix: make button unclickable if disabled

lib/components/SInputYear.vue
Add `disabled` option for SInputYear component.
=> feat: add disabled option for input-year

lib/components/SCardHeader.vue
Make SCardHeader's prop `actions` refish.
=> feat: make header's actions prop refish

lib/validation/rules/index.ts, lib/validation/rules/minValue.ts, lib/validation/validators/index.ts, lib/validation/validators/minValue.ts, test/validation/validators/minValue.spec.ts
This PR implements the validation `minValue`, this is like `maxValue`.
=> feat(validation): add minValue validation

docs/components/inputs/StoryInputNumberEXSeparator.vue, docs/pages/components/inputs-number/index.vue, docs/pages/components/inputs-text/index.vue, lib/components/SInputNumber.vue, lib/components/SInputText.vue, test/components/SInputNumber.spec.ts, test/components/SInputText.spec.ts
Make it possible to show the value of NumberInput with a thousand separator when the focus is out.
To implement it, also change SInputText so that it can have a separate value for display.
=> feat: show value with separator when focus is out

test/components/SAction.spec.ts, test/components/SAlert.spec.ts, test/components/SCard.spec.ts, test/components/SDialog.spec.ts, test/components/SDropdown.spec.ts, test/components/SHeader.spec.ts, test/components/SInputBase.spec.ts, test/components/SInputDay.spec.ts, test/components/SInputMonth.spec.ts, test/components/SInputYMD.spec.ts, test/components/SSheet.spec.ts
Add some tests for the components the coverage of which is low.
- SAction
- SAlert
- SCard
- SDialog
- SDropdown
- SHeader
- SInputBase
- SInputDay
- SInputMonth
=> test: add some tests for components

tests/validation/validators/checked.spec.ts, tests/validation/validators/fileExtension.spec.ts, tests/validation/validators/hms.spec.ts, tests/validation/validators/requiredHms.spec.ts, tests/validation/validators/requiredYmd.spec.ts, tests/validation/validators/ymd.spec.ts, tsconfig.json, vitest.config.ts
Add tests for `validations/validators/`.
=> test: add test for 'checked' validators

docs/components/icons/StoryIcons.vue, lib/components/icons/SIconCircle.vue
=> feat: add circle icon

lib/composables/Grid.ts
Implement `useGrid` function which fill the end of the space on the grid.
```ts
type UseGrid = (options: Option) => { execute: () => void }
interface Option {
containerClass: string
spacerClass?: string
spacerTag?: string
type?: 'fill' | 'fit'
}
```
```ts
useGrid({
containerClass: 'container', // required
spacerClass: 'shim', // default 'spacer'
spacerTag: 'li', // default 'div'
type: 'fill' // default 'fit'
})
```
=> feat: add useGrid

.eslintrc.js, lib/components/SButtonGroup.vue, lib/components/SSheet.vue, lib/types/Utils.ts, stories/components/SButtonGroup.story.vue, stories/components/SDropdown.story.vue, stories/components/SInputFile.story.vue, stories/components/SSteps.story.vue, stories/components/STable.story.vue, tsconfig.json
This PR attempts to tackle some irregularities with `tsconfig.json` such as missing compiler files (notably vitepress config), including `stories` in the project and revising the consequential type issues.
Not sure if these were left out intentionally; nonetheless, the changes to `tsconfig.json` resolve issues that were not visible to the compiler that now is. See comments for more info.
=> chore: resolve tsconfig irregularities

lib/components/STableColumn.vue
=> fix(table): prevent column dialog from going out of screen

lib/components/SDropdownSectionFilter.vue, lib/components/STable.vue, lib/components/STableCellAvatars.vue, lib/components/STableCellPill.vue, lib/components/STableColumn.vue, lib/components/STableFooter.vue, lib/composables/Dropdown.ts
Adjust / Fix the below points.
- Fix z-index of the STable header which was under the avatars.
- Fix empty pill was shown when value is null or undefined.
- Fix the border color of the STableCellAvatars on hover.
- Adjust to make it possible to accept Ref value for DropdownSectionFilterOption.
=> Adjust some related to STable

lib/components/SInputDropdown.vue
=> fix(SInputDropdown): change border color on error

lib/components/STableCellPill.vue
=> fix(table): invalid prop type error thrown on `color` prop (#157)

lib/components/SInputNumber.vue, lib/components/SInputText.vue, stories/components/SInputNumber.story.vue, tests/components/SInputNumber.spec.ts
fix #158
I've also just fixed the code style for this component.
=> fix(input-number): display value style is broken (#158)

lib/components/SInputDropdown.vue, lib/components/SInputDropdownItem.vue, lib/components/SInputDropdownItemAvatar.vue, lib/components/SInputDropdownItemText.vue, stories/components/SInputDropdown.story.vue
=> fix: hide remove icon when only one item is selected and input is non nullable

lib/components/SInputYMD.vue
=> fix(SInputYMD): make `small` the default size

lib/components/SDropdownSectionFilter.vue, lib/components/SDropdownSectionFilterItemAvatar.vue, lib/components/SDropdownSectionFilterItemText.vue
=> fix(dropdown): adjust spacing for text wrap

tests/validation/rules/checked.spec.ts
=> test: ensure `checked` fallback error message is reached

lib/components/STableCell.vue, lib/composables/Table.ts, stories/components/STable.story.vue
=> feat(table): allow callback on cell property

lib/components/STableCell.vue, lib/components/STableCellPills.vue, lib/composables/Table.ts, stories/components/STable.story.vue
=> feat: add STableCellPills component

stories/_support/Board.vue, stories/_support/Utils.ts
=> chore: mock router in stories

lib/components/SInputSelect.vue, tests/components/SInputSelect.spec.ts, vitest.config.ts
=> fix(select): use index as option value

docs/components/input-file.md, docs/components/input-number.md, docs/components/input-radios.md, docs/components/input-select.md, lib/components/SInputBase.vue, lib/composables/Validation.ts, tests/Utils.ts, tests/components/SInputBase.spec.ts
fixes #192 
(it's _slightly_ better, but isn't 100% though)
=> test: add tests for SInputBase

docs/components/table.md, lib/components/STable.vue, lib/components/STableColumn.vue, lib/composables/Table.ts, stories/components/STable.01_Playground.story.vue
=> feat(table): add `resizable` prop

lib/components/SInputDropdown.vue, package.json, pnpm-lock.yaml, stories/components/SInputDropdown.01_Playground.story.vue
fixes #200
Demo (doesn't seem smooth though 👀):
https://user-images.githubusercontent.com/40380293/214350417-a6d5e26c-a627-48ae-8f69-106c3b383694.mov
=> feat: show dropdown on top if input is near viewport bottom

docs/.vitepress/config.ts, docs/components/input-addon.md, docs/components/input-number.md, lib/components/SIcon.vue, lib/components/SInputAddon.vue, lib/components/SInputDropdown.vue, lib/components/SInputNumber.vue, lib/components/SInputText.vue, lib/composables/Dropdown.ts, lib/composables/Flyout.ts, lib/styles/variables.css, stories/components/SInputNumber.02_Addons.story.vue, stories/components/SInputText.02_Addons.story.vue, tests/Utils.ts, tests/components/SInputAddon.spec.ts, tests/components/SInputText.spec.ts
Asana: https://app.asana.com/0/1130160932501704/1203800531766512/f
Resolves #202
I believe I covered all the necessary use cases in Histoire.
=> feat(input): add `addon-*` slots

docs/components/input-file.md, docs/components/input-number.md, docs/components/input-radios.md, docs/components/input-select.md, lib/components/SInputBase.vue, lib/components/SInputCheckbox.vue, lib/components/SInputCheckboxes.vue, lib/components/SInputDate.vue, lib/components/SInputDropdown.vue, lib/components/SInputFile.vue, lib/components/SInputHMS.vue, lib/components/SInputNumber.vue, lib/components/SInputRadio.vue, lib/components/SInputRadios.vue, lib/components/SInputSelect.vue, lib/components/SInputSwitch.vue, lib/components/SInputSwitches.vue, lib/components/SInputText.vue, lib/components/SInputTextarea.vue, lib/components/SInputYMD.vue, lib/components/SSpinner.vue, stories/components/SInputText.01_Playground.story.vue
=> feat: allow showing check state in input components

docs/styles/input-styles.md, lib/components/SInputBase.vue, lib/styles/variables.css
=> feat(input): add `--input-label-font-size` css var (#209)

lib/components/SInputDate.vue, package.json
=> feat(input-date): add `block` option

lib/components/SInputTextarea.vue
=> feat(input-textarea): add `rows="fill"` option

docs/.vitepress/config.ts, docs/components/input-hms.md, lib/components/SInputHMS.vue, stories/components/SInputHMS.01_Playground.story.vue, tests/Utils.ts, tests/components/SInputHMS.spec.ts
=> feat(input-hms): refine styles

docs/.vitepress/config.ts, docs/components/input-ymd.md, lib/components/SInputYMD.vue, stories/components/SInputYMD.01_Playground.story.vue, tests/components/SInputYMD.spec.ts
=> feat(input-ymd): refine styles

lib/components/SDropdownSection.vue, lib/components/SDropdownSectionComponent.vue, lib/composables/Dropdown.ts, stories/styles.css
=> feat(dropdown): add `component` type

lib/components/SInputDate.vue, package.json, pnpm-lock.yaml, stories/components/SInputDate.01_Playground.story.vue, tests/components/SInputDate.spec.ts
This PR adds `size` prop to SInputDate.
Basically the style for each sizes is same as `SInputText`.
=> feat: add size props to SInputDate

lib/components/SInputText.vue
=> fix(input-text): hide overflow

docs/components/table.md, lib/components/STable.vue, lib/components/STableItem.vue, lib/composables/Table.ts, stories/components/STable.01_Playground.story.vue
fixes #239
https://user-images.githubusercontent.com/40380293/230400168-5dbfe1d4-7603-425e-a343-6b01f009dcf2.mov
=> feat(table): add an option to grow a column to fill available space

lib/components/STableCell.vue, lib/components/STableCellState.vue, lib/composables/Table.ts, stories/components/STable.01_Playground.story.vue
=> feat(table): add `TableCellState` type

lib/composables/Grid.ts
=> fix(grid): instantiate MutationObserver on client only (#263)

lib/components/SInputHMS.vue, lib/components/SInputYMD.vue, tests/components/SInputHMS.spec.ts, tests/components/SInputYMD.spec.ts
This PR fixes the issue that it causes the error when we set the placeholder to `SInputYMD` and `SInputHMS` partially.
=> fix: error on set placeholder partially

lib/components/STableColumn.vue, lib/composables/Flyout.ts
Fix the error which occurs when `container` element is null.
=> fix: error on accessing nullable variables

docs/support/num.md, lib/support/Num.ts, tests/support/Num.spec.ts
=> feat(num): add `abbreviate` utility

lib/composables/Form.ts
=> feat(form): allow specifying message in validateAndNotify

lib/components/SButton.vue
unblocks https://github.com/globalbrain/barthlomei/pull/52
=> fix(types): workaround for vue-tsc bug

docs/.vitepress/config.ts, docs/components/link.md, lib/components/SLink.vue, stories/components/SLink.01_Playground.story.vue, tests/components/SLink.spec.ts
=> feat(link): add `external` prop to `SLink` (#293)

lib/components/SDropdownSectionMenu.vue, lib/composables/Dropdown.ts, package.json
=> feat(dropdown): allow disabling menu options

lib/components/SDropdownSection.vue, lib/components/SDropdownSectionComponent.vue, lib/composables/Dropdown.ts
resolves #308, but not sure if it is required
=> feat(dropdown): allow passing props to component

lib/components/SDropdown.vue
=> fix(dropdown): reset white space wrapping

docs/styles/input-styles.md, lib/components/SDropdownSectionFilter.vue, lib/components/SInputHMS.vue, lib/components/SInputText.vue, lib/components/SInputTextarea.vue, lib/components/SInputYMD.vue, lib/styles/variables.css
=> feat(input): enable input `font-family` custom property

docs/components/input-checkbox.md, docs/components/input-checkboxes.md, docs/components/input-radios.md, lib/components/SInputCheckbox.vue, lib/components/SInputCheckboxes.vue, lib/components/SInputRadio.vue, lib/components/SInputRadios.vue, stories/components/SInputCheckbox.01_Playground.story.vue, stories/components/SInputCheckboxes.01_Playground.story.vue, stories/components/SInputRadios.01_Playground.story.vue, tests/components/SInputCheckbox.spec.ts, tests/components/SInputCheckboxes.spec.ts, tests/components/SInputRadios.spec.ts
=> feat(checkbox,radio): add `disabled` prop

docs/components/input-checkbox.md, lib/components/SInputCheckbox.vue, stories/components/SInputCheckbox.02_Indeterminate.story.vue
=> feat(checkbox): allow `indeterminate` as the value

.gitignore
Just adding this here. I used to unstage those every time I commit 😅
=> chore: add vscode settings to gitignore

lib/components/STable.vue, lib/composables/Table.ts, package.json, pnpm-lock.yaml, stories/components/STable.01_Playground.story.vue
=> fix(table): allow using virtual scroll with fixed column

lib/components/SInputBase.vue
=> fix(input): show info tooltip only on click

tests/components/SInputHMS.spec.ts, tests/components/SInputText.spec.ts, tests/components/SInputYMD.spec.ts
=> test: improve SInputText coverage

lib/components/SInputBase.vue
=> fix(input): fix typo in class names

docs/components/table.md, lib/components/STableCell.vue, lib/components/STableCellActions.vue, lib/components/STableHeader.vue, lib/components/STableHeaderActionItem.vue, lib/components/STableHeaderActions.vue, lib/composables/Table.ts, stories/components/STable.01_Playground.story.vue
refer story for usage
still need to fix some things like auto-resize and sticky columns. probably can do them later. this should unblock nia
=> feat(table): add action column type

docs/components/tooltip.md, lib/components/SCardHeader.vue, lib/components/SSheet.vue, lib/components/STableCell.vue, lib/components/STableColumn.vue, lib/components/STableHeader.vue, lib/styles/variables.css
Update `--c-bg-elv-X` colors to match the latest Figma color system. It deprecates `--c-bg-soft`.
=> feat(style): update bg color system

docs/components/input-segments.md, lib/components/SInputBase.vue, lib/components/SInputDate.vue, lib/components/SInputDropdown.vue, lib/components/SInputFile.vue, lib/components/SInputHMS.vue, lib/components/SInputSegments.vue, lib/components/SInputSegmentsOption.vue, lib/components/SInputYMD.vue, stories/components/SInputSegments.02_Modes.story.vue
- fix #391
Update various input styles to the latest.
=> fix(input): update styles to the latest (#391)

docs/components/table.md, lib/components/STableCellPill.vue, lib/composables/Table.ts
=> feat(table): support default color in pill and state cells

docs/.vitepress/config.mts, docs/components/alert.md, lib/components/SAlert.vue, stories/components/SAlert.01_Playground.story.vue
Add `<SAlert>`. Comes with 4 modes:
- `info`
- `success`
- `warning`
- `danger`
```vue
<SAlert mode="info">
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
do eiusmod tempor incididunt ut labore et <a href="#">dolore
magna</a> aliqua. Ut enim ad minim veniam, quis nostrud
exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.
</p>
</SAlert>
```
=> feat(alert): Add `<SAlert>`

docs/.vitepress/config.mts, docs/composables/url.md, lib/composables/Url.ts
=> feat(url): add `useUrlQuerySync` function

lib/composables/Url.ts
=> feat(url): support ref as state

lib/http/Http.ts
We need this in some rare case we don't use Laravel for backend.
```ts
Http.xsrfUrl = false
```
=> feat(http): add option to disable csrf token handling

lib/components/SDropdownSectionFilter.vue, lib/components/SInputCheckboxes.vue, lib/components/SInputDropdown.vue, lib/components/SInputDropdownItem.vue, lib/components/SInputDropdownItemAvatar.vue, lib/components/SInputDropdownItemText.vue, lib/components/SInputRadios.vue, lib/components/SInputSelect.vue, lib/components/SInputSwitches.vue, lib/composables/Dropdown.ts
till we can incrementally adopt generics
=> fix(types): reduce type safety for checkboxes, dropdown, radio values

lib/components/SInputRadios.vue
old code for reference - https://github.com/globalbrain/sefirot/pull/441/files#diff-b7bf67aa5ab343d57e3d002f037f0ce7a788b7bb7f89b3b343c835d3743b69b4
no change is needed in clients
=> feat(input-radio): allow generics for value type

lib/support/Day.ts, lib/support/Utils.ts, tests/support/Day.spec.ts
=> feat(day): allow passing dayjs object to createYmd and createHms

.github/workflows/test.yml
Reverts globalbrain/sefirot#449 (refer https://github.com/globalbrain/sefirot/pull/449#issuecomment-1907647535)
Let's avoid having to change multiple places while updating deps.
Docs - https://github.com/pnpm/action-setup?tab=readme-ov-file#inputs
=> Revert "chore: fix pnpm action"

lib/mixins/Desc.ts
Complement #458
I just added `SDescAvatar` to mixin as other `SDesc` components.
=> fix(desc): add `<SDescAvatar>` to mixin

lib/composables/Url.ts
rewrote it 🫠
The caveats are safe to ignore. I'll fix them later if needed.
=> fix: many bugs with useUrlQuerySync

lib/components/SInputRadio.vue, lib/components/STable.vue, package.json, pnpm-lock.yaml, stories/components/STable.01_Playground.story.vue
=> feat(table): support selecting single row

lib/components/SInputDropdown.vue, lib/components/SInputDropdownItem.vue, lib/components/SInputDropdownItemAvatar.vue, lib/components/SInputDropdownItemText.vue, stories/components/SInputDropdown.01_Playground.story.vue, stories/components/SInputDropdown.02_Avatar_Options.story.vue
The mini size wasn't setting correct height (`32px`). Refactored css formats a bit too. Added size control in Histoire.
=> fix(input-dropdown): support `mini` and `medium` size

lib/validation/validators/slackChannelName.ts, tests/validation/validators/slackChannelName.spec.ts
=> fix(validation): disallow uppercase letters from slack channel name

lib/composables/V.ts
Came across the situation I need to use [`$scope` option](https://vuelidate-next.netlify.app/advanced_usage.html#scope-property) of vuelidate, so enabling passing in the config.
```ts
useV({}, {}, { $scope: 'profile' })
```
Just so that we can:
```ts
const { validation: baseV } = useV({}, {}, { $scope: 'base' })
const { validation: profileV } = useV({}, {}, { $scope: 'profile' })
const { notify } = useVNotification()
// Instead of
const { validation: baseV, notify } = useV({}, {}, { $scope: 'base' })
const { validation: profileV } = useV({}, {}, { $scope: 'profile' })
```
=> feat(validation): enable vuelidate config and extract notification

lib/components/SInputCheckbox.vue, lib/components/SInputRadio.vue
Update disable state of checkbox/radio when it's active.
---
Before:
---
After:
=> fix(input): make active checkbox/radio disable state more visible

lib/components/STable.vue, lib/composables/Table.ts, stories/components/STable.01_Playground.story.vue
closes #496
revert story before merging
=> feat(table): allow disabling selection by user for certain rows

lib/components/SAvatar.vue, stories/components/SAvatar.01_Playground.story.vue
=> fix(avatar): fill image when its not square

lib/components/STableCell.vue, stories/components/STable.01_Playground.story.vue
closes #483
revert story before merging
=> feat(table): highlight selected row

docs/.vitepress/config.mts, docs/components/avatar-stack.md, docs/components/avatar.md, lib/components/SAvatar.vue, lib/components/SAvatarStack.vue, package.json, stories/components/SAvatarStack.01_Playground.story.vue
=> feat(avatar-stack): new component to display stacked avatars

docs/.vitepress/theme/styles.css, docs/components/grid.md, lib/components/SGrid.vue, stories/components/SGrid.01_Playground.story.vue, tests/components/SGrid.spec.ts
=> feat(grid): add support for row and column-specific gap

lib/composables/Error.ts
I had verified the composable in #504. But this was changed last moment so it went undetected.
=> fix(error): typo current error shadowing error store

lib/components/SControlActionBarButton.vue
Now we have a use case for this.
=> feat(control): add `:disabled` and `:tooltip` support on action bar button

docs/components/desc.md, lib/components/SDescText.vue, lib/composables/Markdown.ts, stories/components/SDesc.04_Text.story.vue, stories/components/SDesc.05_Avatar_Many.story.vue
=> feat(desc-text): add linkify option

lib/components/STable.vue, lib/composables/Table.ts, stories/components/STable.01_Playground.story.vue
=> feat(table): allow freezing columns

lib/components/STable.vue
=> feat(table): allow padding-left customization with row selection

lib/components/SInputDropdown.vue, lib/components/SInputHMS.vue, lib/components/SInputYMD.vue, lib/styles/utilities.css, stories/components/SInputDropdown.01_Playground.story.vue, stories/components/SInputDropdown.02_Avatar_Options.story.vue
- close #613
Correctly pass `:size` to base input so that the size prop takes effect.
=> fix(input): pass `:size` to base input (#613)

lib/components/SInputDropdown.vue, stories/components/SInputDropdown.01_Playground.story.vue
=> fix(input-dropdown): show the dropdown even inside container with overflow hidden

lib/composables/Api.ts, lib/composables/App.ts, lib/composables/Http.ts, lib/http/Http.ts, lib/stores/HttpConfig.ts
BREAKING CHANGE: `Http.config` is removed, migrate to `useSetupApp`
=> fix(http): config leaking state in ssr

tests/Utils.ts, tests/composables/Url.spec.ts
Closes #470
I wanted to finish this a long time ago, but I was misled by Copilot's solution and became stuck 😅
=> test: add tests for useUrlQuerySync
