globalbrain/sefirot

lib/components/SInputSelect.vue

fix #24 
This PR fixes where select component have its text over wrapping with chevron icon.

fix: select component text over wrapping chevron icon (#24)

---

lib/support/Util.ts
lib/validation/rules/index.ts
lib/validation/rules/requiredIf.ts
test/validation/rules/requiredIf.spec.ts

This PR adds `requiredIf` validation rule.
```ts
const { data } = useData({
requireEmail: true,
email: null
})
const validation = useValidation(data, {
email: [requiredIf('requireEmail')]
})
```
```ts
const { data } = useData({
status: 'Open',
description: null
})
const validation = useValidation(data, {
description: [requiredIf(d => d.status === 'Open')]
})
```

feat(validation): add `requiredIf` rule

---

lib/components/SPortalModals.vue
package.json
test/components/SButton.spec.ts
test/components/SDropdown.spec.ts
test/components/SGrid.spec.ts
test/components/SInputCheckbox.spec.ts
test/components/SInputCheckboxes.spec.ts
test/components/SInputDate.spec.ts
test/components/SInputNumber.spec.ts
test/components/SInputRadios.spec.ts
test/components/SInputSelect.spec.ts
test/components/SInputSwitch.spec.ts
test/components/SInputSwitches.spec.ts
test/components/SInputText.spec.ts
test/components/SInputTextarea.spec.ts
test/components/SPlaceholderImage.spec.ts
test/components/SPortalModals.spec.ts
test/components/SPortalScreens.spec.ts
test/components/SScreen.spec.ts
test/matchers.ts
test/setup.ts
test/utils.ts
types/mutation-observer.d.ts
yarn.lock

This PR addresses the following:
* improves typescript support
* improves coverage for existing specs
* revises test descriptions & scopes to spec
* adds `toHaveEmittedWith` matcher for component emit readings
* adds the following specs:
* `dropdown`
* `input-switch`
* `input-switches`
* `portal-modals`
* removes `mutation-observer` dependency
`createVue` reduces test noise, is chainable, is scalable, and improves DX.
`createWrapper` gives specs the ability to manufacture and execute repetitive mounting tasks with pre-emptive configuration and option handling. It also infers the component in question to suppress the copious amount of type assertions required to read Vue instances (although the vue-shim ruins that in VCA for Vue 2, still, `<any>` is a last resort).

test: refactor tests for better coverage

---

docs/pages/components/inputs-number/index.vue
lib/components/SInputNumber.vue
lib/components/SInputText.vue

Add `step` props to `SInputNumber` .
This is usable to input a decimal value.
If input decimal value without decimal step attribute,
waring message is shown.

feat: add 'step' props to input number

---

lib/validation/rules/includeSome.ts
lib/validation/rules/index.ts
lib/validation/validators/includeSome.ts
lib/validation/validators/index.ts
test/validation/validators/includeSome.spec.ts

Implement `includeSome` validator which is like `include`.
The difference is this validator can receive array as `other` argument,
and return true if `value` includes one or more of given another value.

feat(validation): implement includeSome

---

.eslintrc.js
lib/composables/Form.ts
lib/types/Utils.ts

Intersects the form validation property as a required key when using rules.

feat: narrow form validation type

---

lib/components/SMarkdown.vue
lib/composables/Markdown.ts
lib/composables/markdown/LinkPlugin.ts
package.json
test/components/SMarkdown.spec.ts
yarn.lock

This PR introduces a standalone component to support markdown rendering. The component requires and implements [markdown-it](https://github.com/markdown-it/markdown-it) as it's choice of renderer. The component can be immersed within existing components as well as externals. The composition is designed to work flexibly to allow custom implementations if necessary.
Basic example:
```vue
<SMarkdown content="Hello **world**" />
<div class="SMarkdown-container">
<p>Hello <strong>world</strong></p>
</div>
```
| Prop | Type | Default | Description
| --- | :---: | :---: | --- |
| `content` | String | – | **Required** - the raw markdown string. 
| `inline` | Boolean | `false` | Renders content without wrapping in `<p>` tags.
| `tag` | String | `'div'` | Renders a custom root element. Useful when …

feat: markdown component

---

docs/components/buttons/StoryButtonEXBlock.vue
docs/components/buttons/StoryButtonEXIcon.vue
docs/components/buttons/StoryButtonEXLoadingState.vue
docs/components/buttons/StoryButtonEXModes.vue
docs/components/buttons/StoryButtonEXRounded.vue
docs/pages/components/buttons/index.vue

This PR sets precedence for documentation of components. There is a clearer distinction in the level of detail for examples and API specs. Going forward, it will provide more clarity between component usage examples (practical explanations) and what the options are (pragmatic descriptions).
- Add missing `rounded` prop spec.
- Reduce loading state timeout for a more prompt demo.
- Clear and concise tone.
- Formatted for consistency.

docs(button): simplify & clear button docs

---

lib/components/SDropdown.vue
lib/components/SInputDropdown.vue
lib/components/SInputSelect.vue
lib/components/SInputText.vue
test/components/SInputSelect.spec.ts

Now `SInputSelect` and `SInputDropdown` can't be focused with tab key.
So enable to focus with tab key by attaching `tabindex`.
**mode:filled**
**mode:outlined**
**mode:filled**
**mode:outlined**

feat: add tabindex to input-selent and input-dropdown

---

lib/components/SModal.vue
lib/components/SPortalModals.vue
lib/composables/Alert.ts
lib/composables/Dialog.ts
lib/composables/Modal.ts
lib/store/alert/index.ts
lib/store/dialog/index.ts
lib/store/modal/index.ts

resolves #66
Breaking changes for `useAlert` which no longer requires an argument on invocation.

feat: explicit modal toggling

---

docs/assets/styles/variables/colors.css
docs/components/inputs/StoryInputTextEXDisabled.vue
docs/pages/components/inputs-number/index.vue
docs/pages/components/inputs-text/index.vue
lib/assets/styles/variables/colors.css
lib/components/SInputNumber.vue
lib/components/SInputText.vue

This PR adds `disabled` option to `SINputText` and `SInputNumber`. Other components would require this feature, but will be starting off with these components.

feat(input-text): add `disabled` feature

---

lib/composables/Utils.ts
test/composables/Utils.spec.ts

This PR modifies the return value from computed utils (`computedOnly` and `computedIfOnly`) to return shallow ref instead of ref. Because ref will unwrap nested ref but computed should not.

fix(utils): return shallow ref from computed utils

---

docs/assets/styles/variables/colors.css
docs/pages/components/inputs-date/index.vue
docs/pages/components/inputs-select/index.vue
docs/pages/components/inputs-textarea/index.vue
lib/assets/styles/variables/colors.css
lib/components/SInputDate.vue
lib/components/SInputSelect.vue
lib/components/SInputTextarea.vue

Add `disbaled` prop to following components same as SInputText.
- SInputDate
- SInputTextarea
- SInputSelect

feat: add disable prop to some input component

---

docs/components/inputs/StoryInputDropdownEXDisabledOptions.vue
docs/components/inputs/StoryInputSelectEXDisabledOptions.vue
docs/pages/components/inputs-dropdown/index.vue
docs/pages/components/inputs-select/index.vue
lib/components/SInputDropdown.vue
lib/components/SInputSelect.vue
lib/composables/Dropdown.ts
test/components/SInputDropdown.spec.ts
test/components/SInputSelect.spec.ts

This PR implements a `disabled` option for the select options of `Select` and `Dropdown`.
The options which `disabled` option is true are not displayed as select options.

feat: add disabled option for select and dropdown

---

docs/components/tooltips/StoryTooltipEXLongText.vue
docs/components/tooltips/StoryTooltipShowcase.vue
docs/pages/components/tooltips/index.vue
lib/components/SCardHeader.vue
lib/components/STooltip.vue
lib/composables/Tooltip.ts

This PR adds markdown support in `Stooltip`. It also fixes issue where tooltip contents go off-screen when it is displayed near edge of the window.

feat(tooltip): add markdown support

---

docs/assets/styles/variables/z-indexes.css
lib/assets/styles/variables/z-indexes.css
lib/components/STooltip.vue

Currently, there is a possibility that the z-index o tooltips is overlapping with other components.
So make it possible to set a z-index for it.

feat: add z-index for SToolTip

---

lib/components/SInputNumber.vue
test/components/SInputNumber.spec.ts

The problem is that the value of help text under Input number is rounded.
Before fix
After fix

fix: add option to toLocaleString for not rounding decimal

---

docs/pages/components/button-group/index.vue
lib/components/SButtonGroup.vue

There is a bug in the button group component that the height is not intended because the border's height was included.
The height was not specified to the button group so `border-box` seemed to be not worked.

fix: the height of each button groups

---

docs/assets/styles/components/c-medium.css
docs/components/inputs/StoryInputTextEXColors.vue
docs/pages/components/inputs-text/index.vue
lib/components/SInputNumber.vue
lib/components/SInputText.vue
test/components/SInputText.spec.ts

This PR implement `color` props in InputText and InputNumber.
The API is like below.
```vue
<SInputNumber
v-model="value"
placeholder="1,000,000"
:color="(value) => value >= 0 ? 'success' : 'danger'"
/>
```

feat: Text color of input text and input number

---

docs/pages/components/inputs-number/index.vue
docs/pages/components/inputs-select/index.vue
docs/pages/components/inputs-text/index.vue
docs/pages/components/inputs-ymd/index.vue
lib/components/SInputSelect.vue

This PR implements the `error-message` props for the SInputSelect component.

feat(input-select): add error-message option for select input

---

docs/assets/styles/variables.css
docs/components/SpecEvents.vue
docs/components/SpecProps.vue
lib/assets/styles/variables.css
lib/components/SGrid.vue
lib/components/SInputCheckbox.vue
lib/components/SInputDate.vue
lib/components/SInputText.vue
lib/components/SInputTextarea.vue
lib/components/SPlaceholderBlank.vue
lib/components/SSnackbar.vue

Some color styles are broken below in dark mode.
- STextInput
- STextareaInput
- SDateInput
- SGrid
- SCheckbox
- SCard
- SPlaceholder
- SSnackbar
- (docs) `props` and `events` section
Basically, this fixes is just replacing the CSS variables which does not support dark-mode to the one which does.

fix: Broken style on dark mode

---

yarn.lock

This PR updates the following dependencies:
- @types/jest
- @types/lodash-es
- @types/prismjs
- @vue/composition-api
- conventional-changelog-cli
- fuse.js
- markdown-it
- prismjs
- ts-jest
- v-calendar
- vue-router
The following dependencies have been held back pending further investigation:
- @vue/test-utils
- @vue/vue2-jest
- jest
- typescript

build: update npm packages

---

lib/components/STableColumn.vue

(to `wip`)
Fix the broken align of the column when grips header to the minus width.

fix: align columns in case of minus width

---

lib/components/SButton.vue
lib/components/SIcon.vue
package.json
pnpm-lock.yaml

partially resolves #140
Migration path:
```diff
- import SIconImage from 'sefirot/components/icons/SIconImage.vue'
+ import iconImageSquare from '@iconify-icons/ph/image-square'
- <SButton :icon="SIconImage" />
+ <SButton :icon="iconImageSquare" />
- import SIconCheck from './icons/SIconCheck.vue'
+ import SIcon from './SIcon.vue'
+ import iconCheck from '@iconify-icons/ph/check'
- <SIconCheck class="check-icon" />
+ <SIcon :icon="iconCheck" class="check-iron" />
```
Custom icons can be defined like this:
```ts
export const customIcon = {
// Icon body: <path d="..." />, required.
body: '<path d="..." />',
// optional:
// Left position of viewBox.
// Defaults to 0.
left: 0, // number
// Top position of viewBox.
// Defaults to 0.
top: 0, // number
// Width of viewBox.
// Defaults to 16. …
```

feat: add icon component and support using iconify in button

---

lib/components/SModal.vue

fixes #145
For accessibility we can also add an event listener on keyup for escape.

fix(modal): listen on mousedown instead of click event

---

lib/components/SInputText.vue

This PR fix below.
- Padding of `mini` and `medium` size with icon (SInputText and SInputNumber)
- Misalignment between `value` and `displayValue` (SInputText and SInputNumber)

fix: add padding to the size other than small

---

lib/components/SInputDropdown.vue

fix(SInputDropdown): prevent text wrapping in placeholder

---

lib/components/STableCell.vue
lib/composables/Table.ts

This PR implements the `component` option for STableCell's type, which can be used for adding custom cell to STable.
The usage is like below.
```vue
<script setup lang="ts">
orders: [
'message',
...
],
columns: {
message: {
label: 'Message',
cell: {
type: 'component',
component: markRaw(VTableCellMessage),
props: {
color: 'info',
message: (value: any) => `${value}`
}
}
}, ...
},
...
})
</script>
```
```vue
// VTableCellMessage.vue (the component that you make)
<script setup lang="ts">
import { computed } from 'vue'
const props = defineProps<{
color: 'info' | 'success'
message: string | ((value: any) => string)
value?: any
record: any
}>()
const _message = computed(() => {
return typeof props.message === 'function' ? props.message(props.value) : props.message
}) …
```

feat: add custom component cell for STable

---

lib/support/Time.ts
tests/support/Time.spec.ts

resolves #185
- adds coverage for `sleep` utility
- replace `Awaited<T>` with builtin utility type

test: `sleep` utility coverage

---

.github/workflows/test.yml
package.json

I found that no package manager and its version are specified in the code base.
I believe it's reasonable to specify `packageManager` field in `package.json` and to use corepack, so that everyone can use same version of same package manager always.
I set everyone as reviewers to hear what you think, or just notification purpose.

chore: enable corepack

---

docs/components/input-number.md
lib/components/SInputNumber.vue
lib/components/SInputText.vue
stories/components/SInputNumber.01_Playground.story.vue
stories/components/SInputNumber.02_Addons.story.vue
stories/components/SInputText.01_Playground.story.vue
stories/components/SInputText.02_Addons.story.vue

I added `unit-before` and `unit-after` props to `SInputText` and `SInputNumber`.
Additionally, I modified Histoire's story controls for us to test UI interactively.

feat: add `unit-*` props to `SInputText` and `SInputNumber`

---

lib/components/SDropdownSection.vue
lib/components/SDropdownSectionActions.vue
lib/composables/Dropdown.ts
stories/components/SDropdown.01_Playground.story.vue

close #225
API is exactly the same as described in #225.

feat(dropdown): add `actions` type (#225)

---

docs/components/table.md
lib/components/STable.vue
lib/components/STableCell.vue
lib/components/STableCellDay.vue
lib/components/STableCellText.vue
lib/composables/Table.ts
lib/styles/variables.css
tests/components/STable.spec.ts

fixes #230
- Sorting and filtering does not affect the summary row (always shown).
- ~~Pagination is not working (at least not on Histoire), so not sure how it will play with that 👀~~
- `onPrev`/`onNext` is empty there, will check if it works fine or not
Also, on filtering, there are a bunch of errors (not related to this PR):
TODO:

feat(table): allow adding summary row

---

lib/components/STableCell.vue

The title explains everything.
I checked the color in Histoire and it looks good to me.

fix(table): fix wrong hover color

---

docs/components/input-ymd.md
lib/components/SInputYMD.vue
tests/Utils.ts
tests/components/SInputYMD.spec.ts

close https://github.com/globalbrain/sefirot/issues/245
Add a `placeholder` prop to SInputYMD component.
This prop must accept together all of the `year`, `month`, and `date`.

feat(SInputYMD): add placeholder props

---

docs/components/input-hms.md
lib/components/SInputHMS.vue
tests/components/SInputHMS.spec.ts

Add a placeholder prop to SInputHMS component.
This prop must accept together all of the hour, minute, and second.
The spec is almost same with the one of `SInputYMD` in this [PR](https://github.com/globalbrain/sefirot/pull/246)

feat(SInputHMS): add placeholder props

---

.gitignore
docs/.vitepress/theme/index.ts
lib/components/STable.vue
lib/components/STableItem.vue
lib/composables/Table.ts
lib/styles/bootstrap.css
lib/types/shims.d.ts
package.json
pnpm-lock.yaml
tests/components/STable.spec.ts

fixes #243
For testing do something like this in story:
```ts
for (let i = 0; i < 10000; ++i) {
data.push({
name: `Artwork ${i}`,
link: 'https://example.com',
status: 'Published',
type: 'Photo',
createdAt: '2022-10-10',
tags: ['Info', 'News', 'Latest']
})
}
```
And set `--table-max-height` to some fixed value (e.g. `65vh` or maybe something complex like `calc(100vh - 5rem)`)
TODO

perf(table): use virtualization and reduce reactivity overhead

---

tests/components/SState.spec.ts

Removes multiple warnings, for example:
```
stderr | tests/components/SState.spec.ts > components/SState > tag is set to `span` by default
[Vue warn]: Missing required prop: "label" 
at <SState ref="VTU_COMPONENT" > 
at <VTUROOT>
```

test(SState): missing required prop

---

tests/components/STable.spec.ts

Suppress warning (and stub as good practice) from [`vue-observe-visibility`](https://github.com/Akryum/vue-observe-visibility/blob/5aa7c4bf5c661ca47f4832c9609683050fd58fe8/src/directives/observe-visibility.js#L87) (dependency of `vue-virtual-scroller`)

test(STable): stub IntersectionObserver

---

lib/components/STable.vue

Fix missing unref `options.orders` which causes error in some cases.

fix(STable): missing unref orders

---

lib/components/STable.vue
lib/composables/Table.ts

x-ref: #266
Virtual scrolling is now disabled by default. Make sure it's only enabled when we don't need sticky column.

fix(table): allow disabling virtual scrolling

---

lib/components/SCard.vue
lib/components/SModal.vue
lib/styles/variables.css
stories/components/SCard.02_Within_Modal.story.vue

- close #281
I went with the Idea 1 approach. I think this is much easier to consume and also, easier to add transition and box shadow.
[See it in action at histoire](https://deploy-preview-282--sefirot-story.netlify.app/story/stories-components-scard-02-within-modal-story-vue?variantId=_default).
The code would look like this.
```html
<SModal :open="isOpen">
<SCard size="small">
...
</SCard>
</SModal>
```

feat(card): add special support when used within modal (#281)

---

lib/components/SDropdown.vue
lib/components/SDropdownSection.vue
lib/components/SDropdownSectionActions.vue
lib/components/SDropdownSectionFilter.vue
lib/components/SDropdownSectionFilterItemAvatar.vue
lib/components/SDropdownSectionFilterItemText.vue
lib/components/SDropdownSectionMenu.vue
stories/components/SDropdown.01_Playground.story.vue
tests/components/SDropdown.spec.ts

Show radio button instead of checkbox on dropdown filter items when `selected` is not an array. Because when selectable item is stored as primitive value, that means user can only select an item a time.
Also I've refined the design as well.

feat(dropdown): show radio button when selected is not array

---

lib/composables/Tooltip.ts

When the tooltip overflows window width, seems like it isn't considering scroll bar width and causing windows to display temporally horizontal scroll bar.
With this, fix I've changed `windoe.outerWidth` to `document.body.clientWidth` to remove scroll bar width.
Also including `SCREEN_PADDING` (16px) when checking the tip position. When positioning tooltip we set 16px padding from the edge of the window. So, the tooltip must not exceed this 16px padding area. Which means the edge of the window should be `document.body.clientWidth - SCREEN_PADDING`.
I don't have windows so I can't directly confirm this but I'm asking to our team member for confirmation.

fix(tooltip): positioning breaking on some edge cases

---

docs/components/table.md
lib/components/STable.vue
lib/components/STableHeader.vue
lib/components/STableHeaderMenu.vue
lib/components/STableHeaderMenuItem.vue
lib/composables/Table.ts
tests/components/STable.spec.ts

- close #249
Adds `menu` option to the table.
```ts
const options = useTable({
menu: [
{
label: 'Option A',
dropdown: {
type: 'menu',
options: [
{ label: 'Option 1', onClick: () => {} },
{ label: 'Option 2', onClick: () => {} },
{ label: 'Option 3', onClick: () => {} }
]
}
}
]
})
```
User can pass in multiple options. And also, by passing in multiple nested array, it groups the menu with divider like shown in the screenshot.
```ts
const options = useTable({
menu: [
[
{ label: 'Option A', dropdown: { ... } },
{ label: 'Option B', dropdown: { ... } }
],
[
{ label: 'Option A', dropdown: { ... } }
]
]
})
```
User can use `state` option to control how the menu button would appear.
- `inactive` – The default state. The menu button fill look slightly muted.
- `active` – The menu button label …

feat(table): add `menu` option (#249)

---

lib/components/STableCellPills.vue

This PR fixes that the background color of the `PillsCell` is different from other cells when the pills' value is empty array.
This is because the cell height is 0 when the pills are empty.

fix(table): No background color is applied when pills is empty array

---

docs/components/table.md
lib/components/STableCell.vue
lib/components/STableCellNumber.vue
lib/composables/Table.ts
stories/components/STable.01_Playground.story.vue

- close #296
Add a cell for number type. Although there is a lot of code duplication with the 'text' cell, I'm leaving it as is for now because we might introduce more number-specific features in the future, and I want to maintain flexibility.
Also, I've largely refactored the docs and separated it into multiple sections.

feat(table): add cell type `number` (#296)

---

lib/components/SDropdownSectionFilter.vue

- close #300 
This was only happening for radio button due to it having `position: relative` but not for checkboxes which have `position: static`. Added `z-index` on search input so that it always gets shown above the filter items.

fix(dropdown): radio button overflows on search input (#300)

---

lib/components/STableCellNumber.vue
tests/components/STable.spec.ts

It was doing falthy check on `v-if` so `0` value on number type cell wasn't displaying any value. Number cell should display any value other than `null` and `undefined`.

fix(table): `0` value not displayed on number type cell

---

docs/components/table.md
lib/components/STableCellText.vue
lib/composables/Table.ts
stories/components/STable.01_Playground.story.vue

Support passing string instead of function to text cell `link` option. Aligns with number type cell, and also we are moving away from these field to be getter.
In the doc, I'm intentionally not documenting getter type because they are pretty much deprecated.

feat(table): support passing plain string to text cell `link` option

---

docs/components/card.md
lib/components/SCard.vue
lib/components/SCardBlock.vue
lib/components/SCardFooter.vue
lib/components/SCardFooterActions.vue

Add `large` option to `<SCard>`. Only relevant when using inside `<SModal>`.
Also add `:space` option to `<SCradFooter>` so that it can have the same spacing with `<SCardBlock>` component. This spacing is needed to align with some of our app design.
Also, improved docs a bit.

feat(card): add `large` size and `space` option to footer

---

docs/.vitepress/config.ts
docs/.vitepress/theme/styles.css
docs/components/grid.md
lib/components/SGrid.vue
lib/components/SGridItem.vue
lib/mixins/Grid.ts
stories/components/SGrid.01_Playground.story.vue
stories/styles.css
tests/components/SGrid.spec.ts

Add `<SGrid>` component.
This is a utility component that makes it a bit easy to define CSS Grid. Especially useful on apps that don't require responsive design. It just reduces a lot of boiler plate CSS and we quite use this a lot.
```html
<SGrid cols="4" gap="24">
<SGridItem span="2">
<div>...</div>
</SGridItem>
<SGridItem span="1">
<div>...</div>
</SGridItem>
</SGrid>
```

feat(grid): add `<SGrid>` component

---

docs/.vitepress/config.ts
docs/components/head.md
lib/components/SHead.vue
lib/components/SHeadLead.vue
lib/components/SHeadTitle.vue
lib/mixins/Head.ts
stories/components/SHead.01_Playground.story.vue
tests/components/SHead.spec.ts

`<SHead>` denotes the title and start of a given section. Mostly used in form layout.
```html
<SHead>
<SHeadTitle>The head title</SHeadTitle>
<SHeadLead>Lorem ipsum dolor sit, amet consectetur.</SHeadLead>
</SHead>
```

feat(head): add `SHead` component

---

lib/mixins/Card.ts
lib/mixins/Grid.ts
lib/mixins/Head.ts
lib/mixins/Sheet.ts

Guess we're moving away from mixins 😎

refactor: use `app.component` instead of `mixin` for global component registration

---

docs/.vitepress/config.ts
docs/components/desc.md
lib/components/SDesc.vue
lib/components/SDescDay.vue
lib/components/SDescEmpty.vue
lib/components/SDescItem.vue
lib/components/SDescLabel.vue
lib/components/SDescLink.vue
lib/components/SDescNumber.vue
lib/components/SDescPill.vue
lib/components/SDescState.vue
lib/components/SDescText.vue
lib/mixins/Desc.ts
stories/components/SDesc.01_Playground.story.vue
stories/components/SDesc.02_Within_Card.story.vue
tests/components/SDesc.spec.ts

`<SDesc>` is a component to create "Description List".
[Refer to the documentation](https://deploy-preview-318--sefirot-docs.netlify.app/components/desc) on how to use this component.

feat(desc): add `SDesc` component

---

lib/components/SGrid.vue
tests/components/SGrid.spec.ts

fix #321 
Can be verified by something like this in `SGrid.01_Playground.story.vue`:
```html
<style scoped>
:deep(.SGrid) {
grid-template-columns: repeat(2, minmax(0, 1fr));
gap: 24px;
}
</style>
```

fix(grid): make styles overridable via CSS

---

docs/components/head.md
lib/components/SHeadTitle.vue
stories/components/SHead.01_Playground.story.vue

Add `:mode` to `<SHeadTitle>`. To create this design along with #325.

feat(head): add `:mode` to title component

---

docs/components/card.md
lib/components/SCard.vue
lib/components/SCardHeaderTitle.vue
stories/components/SCard.01_Playground.story.vue
stories/components/SCard.02_Within_Modal.story.vue

This PR adds `:mode` to `<SCard>` and `<SCardHeaderTitle>`. This is to create this kind of card 👀  It adds "mode" to the border.
Note that `<SCardFooterAction>` already supports this by inheriting `<SButton>` props.

feat(card): add `:mode` to root and header components

---

docs/composables/utils.md
lib/components/SDescDay.vue
lib/components/SDescLink.vue
lib/components/SDescNumber.vue
lib/components/SDescText.vue
lib/composables/Utils.ts
tests/components/SDesc.spec.ts

I found that currently, if we pass null value to `<SDesc>` slots, it will not render `<SDEscEmpty>`. This PR fixes it by checking in the actual slot contents.
I've also added helper utilities to do this as well.
```html
<SDescText></SDescText>
<SDescText>{{ undefined }}</SDescText>
```

fix(desc): empty slot not showing empty state

---

docs/components/desc.md
lib/components/SDescText.vue

This PR adds multi paragraph styling support (add styles) for `<SDescText>`.
```html
<SDescText>
<p>Line one...</p>
<p>Line two...</p>
</SDescText>
```

feat(desc): add multi paragraph support for `<SDescText>`

---

lib/components/SInputYMD.vue

closes #330
`SInputHMS` already have this:
https://github.com/globalbrain/sefirot/blob/97b1bf33b0003c2028192ab1ec899f17be41c694/lib/components/SInputHMS.vue#L279-L291

fix(input-ymd): don't apply hover styles if input is disabled

---

docs/components/desc.md
lib/components/SDesc.vue
lib/components/SDescDay.vue
lib/components/SDescEmpty.vue
lib/components/SDescItem.vue
lib/components/SDescLink.vue
lib/components/SDescNumber.vue
lib/components/SDescPill.vue
lib/components/SDescState.vue
lib/components/SDescText.vue
stories/components/SDesc.01_Playground.story.vue
stories/components/SDesc.02_Row_Direction.story.vue
stories/components/SDesc.03_Within_Card.story.vue

Adds `:dir` option to `SDesc`. This will align label and value horizontally.
To control the divider, I've moved divider to `SDescItem`. And added additional prop to disable it.
Finally, when setting `:dir` to `false`, specify `:labelWidth` to define the width of label area grid.
```html
<SDesc cols="2" gap="24" dir="row" label-width="96" :divider="false">
...
</SDesc>
```
---

feat(desc): add `:dir` option

---

lib/components/SCard.vue

Currently if some content is long, then it expands the grid item size:
After this PR:
Refer https://stackoverflow.com/q/43311943/11613622

fix(card): prevent content from expanding card

---

lib/components/SInputBase.vue

closes #353
Feel free to change it to 640px. I'd used 65ch because that's common with most of the other libraries like primer, tailwind/typography, most chrome and ms projects, etc.

fix(input): limit help and error text width

---

docs/.vitepress/config.mts
docs/components/input-segments.md
lib/components/SInputSegments.vue
lib/components/SInputSegmentsOption.vue
stories/components/SInputSegments.01_Playground.story.vue
stories/components/SInputSegments.02_Modes.story.vue
stories/components/SInputSegments.03_Disable_Option.story.vue

- close #357 
Seems like Generic Components are working 👀 
In addition to the spec in the issue, I've added `options.disable` to be able to disable individual options.

feat(input-segments): add `<SInputSegments>`

---

lib/components/STableCellAvatars.vue

The count of avatars is wrong when more than 2 avatars are shown.
In following example, it looks like there are 4 assignees though there are 3 assignees actually.

fix(table): the count of avatar is wrong on the `STableCellAvatars`

---

docs/.vitepress/config.mts
docs/components/action-list.md
lib/components/SActionList.vue
lib/components/SActionListItem.vue
lib/styles/variables.css
stories/components/SActionList.01_Playground.story.vue
stories/components/SActionList.02_In_Card.story.vue
stories/components/SActionList.03_In_Card_Without_Icons.story.vue
stories/styles.css

- close #358 
Add `<ActionList>`. I have made the type simpler than I described on the issue. Well, this is all we need at the moment.
```ts
interface Props {
list?: ActionList
}
type ActionList = ActionListItem[]
interface ActionListItem {
leadIcon?: IconifyIcon
text: string
link?: string
onClick?(): void
}
```
Also, I have made few css var adjustment to match the latest color system on Figma. `--c-mute` is deprecated in favor of new `--c-bg-mute-1` series. 
---

feat(action-list): add `<ActionList>` (#358)

---

docs/components/button.md
lib/components/SButton.vue
lib/components/STableHeaderActionItem.vue
lib/composables/Table.ts
lib/styles/variables.css
stories/components/SButton.01_Playground.story.vue
stories/components/SButton.02_Sizes.story.vue
stories/components/SButton.03_Types_and_Modes.story.vue
stories/components/SButton.04_Icons.story.vue

Add a new `default` option to `:mode` and organize the color system of the button. This will aline mode of button to other similar component such as `<SPill>` and `<SState>`.
Also, made huge refactor on how to define css inside `<SButton>`. I think I was able to reduce bunch of boilerplates 🔥 
The `mute` mode now looks slightly different. Use the new option `default` to have the same look as before.
---

feat(button)!: add `default` mode and organize color system

---

lib/components/SInputImage.vue

input element wasn't being reset, so that change event is not triggered unless you're uploading different image

fix(image): reset input element on remove

---

lib/components/SInputDate.vue

No related issues.
When `disabled` prop of `SInputDate` component is set true, Vue show the following warning:
> [Vue warn]: v-on with no argument expects an object value.
This PR fixes runtime type error and prevent the warning.

fix(input-date): fix prop value to prevent warning

---

docs/.vitepress/config.mts
docs/components/m.md
lib/components/SM.vue
lib/components/SMFade.vue
stories/components/SM.01_Playground.story.vue
stories/components/SM.02_Presets_SMFade.story.vue
stories/styles.css

Add `<SM>` (motion). Inspired by [VueUse Motion](https://motion.vueuse.org/), but more simplified and opinionated.
This component adds subtle animation when an element enters the view port. Most of the time, this component should only be used for marketing websites where these kind of micro animation adds slight value to the representation of the contents.
[Test it out on Histoire](https://deploy-preview-370--sefirot-story.netlify.app/story/stories-components-sm-01-playground-story-vue?variantId=_default)
Wrap any component with `<SM>` and adjust the parameters.
```html
<SM opacity="0" y="8px">
...
</SM>
```
Naming it `<SM>` since when used, this component shows up quite a lot. Plus, we can add more "presets" on how the animation works. In this PR, I've added `SMFade` where opacity …

feat(m): add `<SM>` (motion) component

---

lib/components/STable.vue
stories/components/STable.01_Playground.story.vue

another heads up, like we make the last column `resizable: false` everywhere, while using actions, we should make the last "two" columns `resizable: false`.

fix(table): don't grow actions column

---

lib/styles/variables.css

Adjust `--c-bg-elv` color on light mode. It makes `--c-bg-elv` slightly darker.
The issue is, while `bg-elv` works the same way n both Light/Dark mode where the higher the number is, it gets brighter (elevated), light mode has upper limit on how bright it can be and that is `bg-elv-3` where it reaches `#ffffff`.
Therefore `bg-elv-4` becomes darker on light mode. This is because `bg-elv-4` is used to distinguish the element from `bg-elv-2` and `bg-elv-3`.
Until now, we were using the same color for both `bg-elv-2` and `bg-elv-4`. But it is a bit hard on eye when used on component like Card (with header) or table.
This change makes `bg-elv-2` a bit darker so that it can be a bit more easier to see the difference. Aiding the visuals.
The contrast might not be enough compared to dark mode. …

fix(style): adjust `bg-elv` color for light mode

---

docs/components/table.md
lib/components/STableCell.vue
lib/components/STableCellActions.vue
lib/composables/Table.ts

This might be helpful in cases where we don't want to show delete button, say, in front of current user / only sysadmin.
Slightly breaking change - value is removed from onClick as it's always undefined.

feat(table): allow conditionally showing action items

---

docs/components/pill.md
docs/components/state.md
lib/components/SPill.vue
lib/components/SState.vue
lib/styles/variables.css
stories/components/SPill.01_Playground.story.vue
stories/components/SPill.02_Sizes.story.vue
stories/components/SPill.03_Types_and_Modes.story.vue
stories/components/SState.01_Playground.story.vue
stories/components/SState.02_Sizes.story.vue
stories/components/SState.03_Modes.story.vue
tests/components/SPill.spec.ts

Add `default` mode to `<SPill>` and `<SState>`.
This aligns with how `<SButton>` mode works right now. Also, change the shape of `<SState>` to be round, as it is in the latest Figma design.
Plus, I've re-organized docs for these 2 components to match the latest pattern used in `<SM>`.
---

feat(pill,state): add `default` mode

---

docs/.vitepress/config.mts
docs/components/w.md
docs/styles/utility-classes.md
lib/components/SW.vue
lib/styles/bootstrap.css
lib/styles/utilities.css
stories/components/SW.01_Playground.story.vue
stories/styles.css

Add `<SW>` component.
We use this a lot in marketing sites, such as GB website and XLIMIT website.
Also added new CSS utility classes. We could add these classes in places where the component used a lot and creating scoped css for each is too much.

feat(w): add `<SW>` (word) component

---

lib/components/STable.vue
lib/components/STableCellActions.vue
lib/support/Text.ts
lib/types/shims.d.ts
lib/types/vue-shims.d.ts
stories/components/STable.01_Playground.story.vue

closes #377
---
Also adjusted the code to always left align the action cell items. It was looking weird when some of the icons are hidden:
Before:
After:
Not sure though which is more desirable.
---
Close  #382 if merging this. `show` is the recommended way if you want to hide some icons and use auto resize at the same time. This PR won't work when actions.cell is a function.

feat(table): auto resize actions column

---

docs/components/card.md
lib/components/SCard.vue
stories/components/SCard.01_Playground.story.vue
stories/components/SCard.02_Within_Modal.story.vue

Add `xlarge` and `xxlarge` size to `<SCard>`.
The rule is when screen is big enough to hit this size, the card should have `32px` padding both left/right side against our main content width.
Card max width is a bit smaller than main content width we usually use for our apps. Which is usually max `1216px`.
So that when modal content hits its max size, it still have good padding left/right compared to underlining contents.

feat(card): add `xlarge` and `xxlarge` size

---

lib/components/SMFade.vue

`SMFade` default value for `:once` was set to false due to boolean default. Well maybe I should have named this prop `:always` or something and made it default to `false` 😅

fix(m): make `SMFade` `:once` default to `true`

---

lib/components/SInputBase.vue

Currently, label can't have line break. If it does, it leaks into input box. Labels shouldn't be long enough to have line break in the first place, but this is sometimes unavoidable on mobile.
Also cleaned up a bit on info and note combination handling. A bit hacky so I might wanna refactor in the future, but this should work for now 🤔

fix(input): allow line break on label

---

docs/components/desc.md
lib/components/SDescFile.vue
lib/components/SDescItem.vue
lib/mixins/Desc.ts
stories/components/SDesc.01_Playground.story.vue
stories/components/SDesc.02_Row_Direction.story.vue
stories/components/SDesc.03_Within_Card.story.vue

Add `<SDescFile>` component.
This is useful to display attached file in desc grid. The "Download" button will just execute the callback `onDownload` function, and user should handle whatever it needs to do to download the file.
```vue
<SDesc>
<SDescItem>
<SDescLabel>Attachments</SDescLabel>
<SDescFile
:file="[
{ name: 'John-Doe-Resume-19851010.pdf', onDownload: () => {} },
{ name: 'profile-photo.jpg', onDownload: () => {} }
]"
/>
</SDescItem>
</SDesc>
```
---

feat(desc): add `<SDescFile>`

---

docs/.vitepress/config.mts
docs/components/card.md
docs/components/content.md
docs/components/divider.md
docs/components/doc.md
lib/components/SCardBlock.vue
lib/components/SCardFooter.vue
lib/components/SCardFooterActions.vue
lib/components/SContent.vue
lib/components/SDivider.vue
lib/components/SDoc.vue
lib/components/SDocSection.vue
stories/components/SDoc.01_Playground.story.vue
stories/components/SDoc.02_Within_Card.story.vue
stories/styles.css

Add `<SDoc>` component to build consistently styled form and dialogs.
This PR also:
- Adds `<SDivider>`.
- Add support for `h1` and `h2` in `<SContent>`.
- Add `xwide` option to `SCardBlock` and `SCardFooter`.
```vue
<SDoc>
<SDocSection class="header">
<SContent>
<h1>Title of the content</h1>
<p>Lorem ipsum...</p>
</SContent>
</SDocSection>
<SDivider />
<SDocSection class="account-info">
<SContent>
<h2>Section title</h2>
<p>Lorem ipsum...</p>
</SContent>
<SGrid gap="24">
<SGridItem>
<SInputText
label="Name"
placeholder="John Doe"
:model-value="null"
/>
</SGridItem>
<SGridItem>
<SInputText
type="email"
label="Email"
placeholder="john.doe@example.com"
:model-value="null"
/>
</SGridItem>
</SGrid>
</SDocSection>
</SDoc>
```
---

feat(doc): add `<SDoc>`

---

lib/composables/Url.ts

The value could be for example array, if the stored object is array. So, I guess it makes sense to make this `any` 👀 
Or should we scope this to something like string or object or array?
```ts
useUrlQuerySync(options, {
casts: {
// It is indeed array but type error.
// No `map`, since value is typed as `string`.
'tags': (v) => v.map(Number),
}
})
```

fix(url): change cast callback value type to any

---

docs/.vitepress/config.mts
docs/components/local-nav.md
lib/components/SLocalNav.vue
lib/components/SLocalNavMenu.vue
lib/components/SLocalNavTitle.vue
stories/components/SLocalNav.01_Playground.story.vue

Adds local nav component.
```vue
<script setup lang="ts">
const navTitle = [
{ text: 'ABC Company', link: '#' },
{ text: 'Series A' }
]
const navMenu = [
[
{ icon: IconActivity, text: 'Overview', link: '#', active: true },
{ icon: IconCurrencyCircleDollar, text: 'Payments', link: '#' }
],
[
{ icon: IconGear, text: 'Settings', link: '#' }
]
]
</script>
<template>
<SLocalNav :title="navTitle" :menu="navMenu" />
</template>
```
---

feat(local-nav): add `<SLocalNav>`

---

lib/components/STableCell.vue
lib/components/STableCellAvatars.vue
lib/composables/Table.ts
stories/components/STable.01_Playground.story.vue

- close #416
Now we can control how many avatars do we wanna show on table cell. We can also set count to `0` to hide avatars or names.
```ts
columns: {
authors: {
label: 'Authors',
cell: (authors) => ({
type: 'avatars',
avatars: authors,
avatarCount: 5,
nameCount: 3
})
}
}
})
```

feat(table): add option to control display count of avatars (#416)

---

lib/components/STable.vue
lib/composables/Table.ts

Currently, if we use `computed` on `columns`, the types get fucked up. Usually, we wanna use reactive value for `show` option, so for now, enabling `ref` value on show to bypass the issue.
```ts
columns: {
name: {
// Now we can do this.
show: () => shouldShow.value
}
}
})
```

feat(table): accept ref on column show option

---

lib/components/SButton.vue
lib/components/SCard.vue
lib/components/SCardBlock.vue
lib/components/SControl.vue
lib/components/SControlButton.vue
lib/components/SControlCenter.vue
lib/components/SControlInputSearch.vue
lib/components/SControlLeft.vue
lib/components/SControlPagination.vue
lib/components/SControlRight.vue
lib/components/SControlText.vue
lib/components/SInputText.vue
lib/components/SPagination.vue
lib/components/STable.vue
lib/components/STableColumn.vue
lib/components/SW.vue
lib/composables/Card.ts
lib/composables/Control.ts
lib/composables/Table.ts
lib/mixins/Control.ts
lib/styles/utilities.css
stories/components/SCard.01_Playground.story.vue
stories/components/SCard.02_Within_Modal.story.vue
stories/components/STable.01_Playground.story.vue
stories/components/STable.02_Legacy.story.vue

OK this includes a lot more changes than I expected but here it is.
- Add `:trail-icon` option to `<SButton>`.
- Add `<SPagination>` component.
- Add `<SControl>` and its child components.
- Add many utility css classes.
Here is how you would build table with this changes.
```vue
<SCard>
<SCardBlock size="medium" class="s-px-12">
<SControl>
<SControlLeft>
<SControlInputSearch class="s-max-w-320" :model-value="null" />
<SControlButton type="outline" mode="mute" label="Reset filters" @click="resetFilters" />
</SControlLeft>
<SControlRight>
<SControlButton mode="info" label="New item" />
</SControlRight>
</SControl>
</SCardBlock>
<SCardBlock>
<STable class="table" :options="table" />
</SCardBlock>
<SCardBlock size="medium" class="s-px-12">
<SControl>
<SControlRight>
<SControlPagination …
```

feat: many additions for new table structure

---

lib/components/SActionList.vue
lib/components/SActionListItem.vue
lib/components/SActionMenu.vue
lib/components/SControlActionMenu.vue
lib/components/SDropdown.vue
lib/components/SDropdownSectionMenu.vue
lib/composables/Dropdown.ts
lib/mixins/Control.ts
package.json
pnpm-lock.yaml
stories/components/SActionList.01_Playground.story.vue
stories/components/SActionList.02_In_Card.story.vue
stories/components/SActionList.03_In_Card_Without_Icons.story.vue
stories/components/SActionMenu.01_Playground.story.vue
tests/components/STable.spec.ts

Add action menu component, inspired by [GitHub Primer: Action Menu](https://primer.style/components/action-menu).
It also includes change where `DropdownSectionMenu` is now directly integrated and using `<SActionList>` to display the menu.
Adjusting the key differences as well, where action list uses `text`, dropdown is using `label`. `label` is deprecated 👀 
```vue
<SActionMenu
label="Open menu"
:options="dropdownOptions"
/>
```

feat(action-menu): add `<SActionMenu>`

---

lib/components/SDropdownSection.vue
lib/components/SDropdownSectionDateRange.vue
lib/components/SDropdownSectionDateRangeDateFromTo.vue
lib/components/SDropdownSectionDateRangeYear.vue
lib/components/SDropdownSectionDateRangeYearHalf.vue
lib/components/SDropdownSectionDateRangeYearQuarter.vue
lib/composables/Dropdown.ts
lib/composables/V.ts
lib/support/DateRange.ts
stories/components/SDropdown.02_Section_Date_Range.story.vue

Add dropdown section to handle "Date Range" selection.
I've added new class `DateRange` which holds `from` and `to` dates, with `presets`. The usage would look like this.
```vue
<script setup lang="ts">
// Create a new `DateRange` instance.
const range = shallowRef(new DateRange())
const sections = [
createDropdownDateRange({
range,
// This callback will only be called when user hits
// `Apply` button in dropdown menu.
onApply: (r) => { range.value = r }
})
]
// Access `from` and `to` value.
range.value.getFrom() // Day instance
range.value.getTo()   // Day instance
</script>
<template>
<SDropdown :sections="sections" />
</template>
```
You can define custom preset as a default value by creating the preset at the beginning.
```ts
const range = shallowRef(
new DateRange.setPreset(
new …
```

feat(dropdown): add date range section

---

lib/composables/D.ts
tests/composables/D.spec.ts

`init` was not working when executed multiple times. We need to parse the stored json when executing init, not upfront. Cause otherwise the `initialData` are passed as reference and init no longer works when hit 2nd time.

fix(d): make init work multiple times

---

lib/composables/Lang.ts

closes #422
I don't think we need reactivity here. `useNavigatorLanguage` changes the language ref when a browser fires `languagechange` event, which in our case doesn't happen IG (you need to change preferred languages in browser settings to trigger it.)

feat(lang): add useBrowserLang function

---

lib/composables/Api.ts
lib/http/Http.ts

Bit of a breaking change:
```ts
// earlier -- Http.base = '/foo' -- now:
Http.config({
baseURL: '/foo'
})
```

feat(http): allow overriding fetch handler

---

.github/workflows/test.yml

Complement #448
I just added pnpm version and add `run_install: false` because the following action do that.

chore: fix pnpm action

---

lib/components/SInputRadios.vue

Nick gave me some idea in vue internal discord. 
Still need some way to avoid `null as NullValue`. Will see. After that we can implement generics for dropdown, etc.

refactor(input-radios): improve types

---

docs/components/desc.md
lib/components/SDescAvatar.vue
stories/components/SDesc.01_Playground.story.vue

- close #455
At the moment, I'm limiting this component to show only 1 user. Not sure yet how to display multiple users, especially combined with their names 🤔 
```vue
<SDescItem span="2">
<SDescLabel>Account</SDescLabel>
<SDescAvatar
:avatar="{
avatar: 'https://i.pravatar.cc/64?img=1',
name: 'margot.foster'
}"
/>
</SDescItem>
```

feat(desc): add `<SDescAvatar>` (#455)

---

lib/components/SDescAvatar.vue

Fix #458
I found `SDescAvatar` shows avatar only when it's truthy, which is different from how `SAvatar` works.
So I removed if-condition for `SAvatar` to have a control on what to show: image or initial of name.
@kiaking 
If this is intended, please let me know and close this PR.

fix(desc): show non-image avatar correctly

---

lib/components/SControlActionBar.vue
lib/components/SControlActionBarButton.vue
lib/components/SControlActionBarClose.vue
lib/components/SControlActionBarCollapse.vue
lib/mixins/Control.ts
stories/components/SCard.01_Playground.story.vue
stories/components/SCard.02_Within_Modal.story.vue

Add "Action Bar" type component support for `<SControl>`. Inspired by [GitHub Primer: ActionBar](https://primer.style/components/action-bar).
We need this since ordinary `<SControlButton>` will get gap between buttons (which it should), but these Action Bar buttons that only contains icon should not have gap in between.
In the future, we could have generic `<SActionBar>` that can be used outside of `<SControl>` too, but for now, until we get solid use case for that, I'm scoping it under to `<SControl>`.
It adds following components that can be used inside `<SControl>`.
- `<SControlActionBar>`
- `<SControlActionBarButton>` - Generic button component.
- `<SControlActionBarClose>` - Shorthand for close (X) button.
- `<SControlActionBarCollapse>` - Shorthand for collapse button.
```vue
<SCard …
```

feat(control): add "Action Bar" type support

---

lib/components/SDescNumber.vue

- close #461 
Add `:lead-unit` and `:trail-unit` option to `<SDescNumber>`.

feat(desc): add lead/trail nit option to `<SDescNumber>`

---

lib/composables/Api.ts

Before:
```ts
export function usePostPage(options: MaybeRefOrGetter<UsePostPageOptions>) {
const query = useQuery(async (http) => {...})
watch(() => toValue(options), query.execute, { deep: true })
return query
}
```
After:
```ts
export function usePostPage(options: MaybeRefOrGetter<UsePostPageOptions>) {
return useQuery(async (http) => {...}, { watch: () => toValue(options) })
}
```
Nuxt's `useAsyncData` also supports passing watch sources, so `useQuerySsr` already supports this.

feat(api): allow watching options in useQuery

---

lib/components/SAvatar.vue
stories/components/SAvatar.01_Playground.story.vue

Add more size option to `<SAvatar>`.
- `jumbo` - `48px` big. Adding this to be more consistent with `<SButton>` sizing.
- `fill` - Custom size that fills the parent container. When we want avatar bigger than 48px, use this.
One issue with `fill` option is that it's hard to set `font-size` for name initial when the user don't have avatar image.
@brc-dd 
Do you know any tricks to like set font size dynamically based on parent container? If not, I think we can stick to `font-size: 20px` I've set. We should only use `fill` when we need big avatar and that's quite rare case so 👀

feat(avatar): add more size option

---

docs/components/desc.md
lib/components/SDescAvatar.vue
stories/components/SDesc.04_Avatar_Many.story.vue

```vue
<SDesc cols="2" gap="24">
<SDescItem span="1">
<SDescLabel value="Status" />
<SDescAvatar :avatar="[
{ avatar: "/path/to/avatar.jpg", name: "John Doe" },
{ avatar: "/path/to/avatar.jpg", name: "Jane Doe" }
]" />
</SDescItem>
</SDesc>
```

feat(desc): enable passing multiple avatars to `<SDescAvatar>`

---

lib/components/STableCellState.vue

This should have been like this from beginning to align the size with pill.

fix(table): use `mini` size for state cell

---

lib/components/SDropdown.vue
lib/components/SDropdownSectionFilter.vue
lib/components/SDropdownSectionFilterItemAvatar.vue
lib/components/SInputDropdownItemText.vue
stories/components/SInputDropdown.01_Playground.story.vue
stories/components/SInputDropdown.02_Avatar_Options.story.vue

1\. Filter input didn't had bg color.
---
2\. Cut off the last item so that it's easier to see it's scrollable.
---
3\. Couldn't reproduce in Sefirot but for some reason Avatar items weren't showing the text due to its line height becoming `0`. So I set line height explicitly.

fix(input-dropdown): various fixes

---

lib/composables/Policy.ts

closes #419
Usage:
```ts
import {
type Policy,
type PolicyResponse,
type PolicyHelpers as SefirotPolicyHelpers,
usePolicy as sefirotUsePolicy
} from 'sefirot/composables/Policy'
interface PolicyHelpers<Code extends string | undefined = undefined>
extends SefirotPolicyHelpers<Code> {
user: { admin: boolean }
}
function usePolicy<Code extends string | undefined = undefined>(
fn: (helpers: PolicyHelpers<Code>) => PolicyResponse<Code>
): Policy<Code> {
const user = { admin: true }
return sefirotUsePolicy((helpers) => {
return fn({ ...helpers, user })
})
}
// ...
import { type Policy, usePolicy } from './Policy'
function canDoFoo(): Policy<'foo' | 'bar'> {
return usePolicy(({ user, allow, deny }) => {
return user.admin ? allow('foo') : deny('bar')
})
}
function canDoBar(): Policy {
return …
```

feat: add policy composable

---

lib/validation/Rule.ts
lib/validation/rules/requiredIf.ts

Seems like when validator is async, we need to wrap the validation with [`withAsync` helper](https://vuelidate-next.netlify.app/custom_validators.html#async-validators).
Added `async` option to `createRule`.

fix(validation): use `withAsync` for async rule

---

lib/components/STooltip.vue

closes #468
It's a minor breaking change. One would need to use provided slots + SMarkdown instead if they want the tooltips to render markdown too. This change may also affect buttons and input elements.

fix(tooltip): dont render markdown by default

---

lib/composables/Url.ts

resolves sentry#5090679546
target[key] can be undefined in certain cases in those cases calling splice will throw error. splice call is there to maintain reactivity in array but if there is nothing by default there is no need to maintain reactivity

fix(url): handle array value when corresponding target is non-array

---

lib/components/STableCellDay.vue
lib/components/STableCellNumber.vue
lib/components/STableCellPill.vue
lib/components/STableCellPills.vue
lib/composables/Table.ts

`value` in cell components could be anything, because this is what we get when `order` name matches with record field name. And it don't even have to exist in the record.
Also, `pills` option was only taking function so fixed it.

fix(table): correct wrong types and make pills accept array

---

docs/components/alert.md
docs/components/avatar-stack.md
docs/components/avatar.md
docs/index.md
docs/styles/colors.md

Task Done:
1. Removed Typos from Docs (.md) files   
- alert.md
- avatar-stack.md
- avatar.md
- index.md
- colors.md
2. Updated avatar-satck.md and avatar.md files as of changes done in PR: #475

docs: fix typos

---

package.json
pnpm-lock.yaml

I had accidentally bumped it in #504. v0.17 breaks reactivity and bunch of other stuff due to suspense.

chore: lock histoire to 0.16

---

lib/validation/Rule.ts
lib/validation/rules/requiredHmsIf.ts
lib/validation/rules/requiredIf.ts
lib/validation/rules/requiredYmdIf.ts
tests/validation/rules/requiredHmsIf.spec.ts
tests/validation/rules/requiredIf.spec.ts
tests/validation/rules/requiredYmdIf.spec.ts

Reactivity in rules were not working. Seems like we need explicitly pass in reactive props into `params`.
```ts
export function requiredIf(
condition: RequiredIfCondition,
msg?: string
) {
return createRule({
async: true,
params: { condition }, // <- This one!
message: ({ lang }) => msg ?? message[lang],
validation: (value) => baseRequiredIf(value, condition)
})
}
```

fix(validation): support reactivity for properties

---

docs/composables/api.md
lib/composables/Api.ts

Adds `assign` option to `useQuery.execute`. It's helpful while implementing functionality like "load more".
When assign is false, `loading.value` will not be set to `true` before fetching - this is to avoid showing spinner - and calling execute won't update `query.data` - one would need to manually merge the returned data with existing one.
Example:
```ts
const query = useQuery(...)
async function loadMore(): Promise<void> {
const res = await query.execute({ assign: false })
;(query.data.value ??= {}).push(...res)
}
}
```

feat(api): allow executing queries without assigning result to data

---

lib/components/SControlActionBarButton.vue
stories/components/SCard.01_Playground.story.vue

No related issues.
I added a way to render `SControlActionBarButton` as a link just because we came to need it in our products.

feat(card): support action bar button as link

---

docs/network-requests/http.md
lib/http/Http.ts

don't merge yet, I'll test it out first
TODO

feat(http): support sending files along with json

---

docs/components/local-nav.md
lib/components/SLocalNav.vue
lib/components/SLocalNavAvatar.vue
lib/components/SLocalNavDescription.vue
stories/components/SLocalNav.02_Avatar.story.vue

feat(local-nav): add `:avatar` and `:description`

---

docs/.vitepress/config.mts
docs/components/indicator.md
lib/components/SIndicator.vue
stories/components/SIndicator.01_Playground.story.vue
stories/components/SIndicator.02_States.story.vue

I've changed props a bit from the issue.
```vue
<SIndicator state="running" />
```
```ts
interface Props {
size?: Size
state: State
mode?: Mode
}
type Size =
| 'nano'
| 'mini'
| 'small'
| 'medium'
| 'large'
| 'jumbo'
type State =
| 'pending'
| 'ready'
| 'queued'
| 'running'
| 'completed'
| 'failed'
type Mode =
| 'colored'
| 'monochrome'
```

feat(indicator): add `<SIndicator>` component

---

package.json
pnpm-lock.yaml

No related issues.
Some products install `dayjs` as their own dependency whose version is different from Sefirot's dependency version.
I got a type error during development.
This PR is to make `dayjs` a peer-dependency so that its version can be automatically checked in Sefirot user products.

fix: set `dayjs` as peer-dependency

---

docs/components/login-page.md
lib/components/SLoginPage.vue
lib/components/SLoginPagePasswordDialog.vue
stories/components/SLoginPage.01_Playground.story.vue

Add password action to the `<SLoginPage>`.
It will also show email/password dialog and handle validations. We can await inside `onSubmit` function to show loading spinner on the form.
```ts
const actions = [
{
type: 'password',
async onSubmit(email, password) {
// The email/password dialog will show loading spinner
// while this promise is being awaited
await login(email, password)
}
}
]
```
---

feat(login-page): add password action

---

docs/.vitepress/config.ts
docs/components/input-file-upload.md
docs/support/file.md
lib/components/SInputBase.vue
lib/components/SInputFileUpload.vue
lib/components/SInputFileUploadItem.vue
lib/support/File.ts
stories/components/SInputFileUpload.01_Playground.story.vue

- close #544 
I've also:
- Add new helper function `formatSize` to get total file size text like `12.32MB`.
- Add new scoped slot to `<SInputBase>` to get whether the input has error or not. Bacause it is easier to apply `mode` option to `SCard`.
I haven't added validation feature for each item. It is not required at the moment, and I wasn't still not sure what was the best way to go about it 🤔 
---

feat(input): add `<SInputFileUpload>`

---

lib/shim.d.ts
package.json
pnpm-lock.yaml

See https://github.com/nathanreyes/v-calendar/issues/1498

fix(input-date): pin v-calendar to fix vue 3.5 compat issue

---

lib/components/SAlert.vue

Because seems like `:slotted` will stop working if we have nested component which very often happens with `<STrans>`.
```html
<SAlert>
<STrans lang="en"><p>Lorem ipsum...</p></STrans>
</SAlert>
```

fix(alert): use `:deep` instead of `:slotted` to style elements

---

lib/styles/base.css
stories/styles.css

Mainly to make font looks as close to Figma. We don't need to add this to VitePress since it already does it in the theme.

feat(style): set font antialias

---

docs/components/button.md
lib/styles/variables.css

decrease contrast between border and background
increase contrast between text and background
Status: needs discussion
before
after
not disabled (for reference)

style(button): adjust colors for fill + disabled buttons

---

docs/components/local-nav.md
lib/components/SLocalNav.vue
lib/components/SLocalNavActions.vue
lib/components/SLocalNavTitle.vue
stories/components/SLocalNav.01_Playground.story.vue

Adds actions (buttons) to local nav.

feat(local-nav): add `:actions` option

---

lib/components/STableCell.vue
lib/components/STableCellPath.vue
lib/composables/Table.ts

Add a cell type to display "Path" like data (directory path, breadcrumbs, etc).
```ts
const data = [
{ path: ['Folder A', 'file-a.png'] },
{ path: ['Folder B', 'file-b.png'] }
]
records: data,
orders: ['path'],
columns: {
path: {
label: 'Path',
cell: (_, record) => ({
type: 'path',
items: record.path.map((p) => ({
label: p,
link: `https://example.com/${p}`
}))
})
}
}
})
```
---

feat(table): add cell type "Path"

---

lib/components/SIndicator.vue
lib/components/STableCell.vue
lib/components/STableCellIndicator.vue
lib/composables/Table.ts
stories/components/SIndicator.01_Playground.story.vue
stories/components/SIndicator.02_States.story.vue

Adds cell type that uses `<SIndicator>`. This PR also adds a new state "Aborted" to the `<SIndicator>`.
```ts
const data = [
{ progress: { state: 'completed', label: 'Completed' } },
{ progress: { state: 'running', label: 'In Progress' } },
{ progress: { state: 'aboretd', label: 'Aborted' } }
]
records: data,
orders: ['progress'],
columns: {
progress: {
label: 'Progress',
cell: (_, record) => ({
type: 'indicator',
state: record.progress.state,
label: record.progress.label
})
}
}
})
```
---

feat(table): add cell type "Indicator"

---

lib/components/SIndicator.vue
lib/components/SInputFileUpload.vue
lib/components/SInputFileUploadItem.vue
stories/components/SInputFileUpload.01_Playground.story.vue

Add droppable file selection and individual item state support to `<SinputFileUpload>`.
In order to keep the backward compatibility, the model value accepts both `File[]` and the new `FileObject[]`, and must define `:model-type="object"` when using `FileObject[]` as model value.
```vue
<script setup lang="ts>
const { data } = useData({
files: [
{ file: File, indicatorType: 'running', canRemove: false }
]
})
const rules = {
maxFileSize: maxFileSize('1mb')
}
</script>
<template>
<SInputFIleUpload
model-type="object"
:v-model="data.files"
:rules="rules"
/>
</template>
```
---

feat(input-file-upload): add droppable and indicator support

---

lib/composables/Url.ts

feat(composables/Url): observe `route.path` in `useUrlQuerySync` to preserve state during navigation

---

lib/composables/App.ts
lib/composables/Http.ts
lib/composables/Lang.ts
lib/composables/Theme.ts

So we can do this now.
```ts
import { useSetupApp } from 'sefirot/composables/App'
const setupApp = useSetupApp()
setupApp(signedInUser, {
http: {
baseUrl: '/backend/'
}
})
```

feat: add app setup composables

---

lib/components/SDescFile.vue
lib/components/SDescItem.vue
lib/components/SDescLabel.vue
stories/components/SDesc.01_Playground.story.vue

Add option to show "actions" in `<SDesc>`. It can have simple buttons and action menu for dropdown.
This PR increases desc label font size to 14 and height to 28px in order to have enough space to show buttons.
Adding actions with `<SDesc dir="row">` is not supported.
```vue
<script setup lang="ts">
import IconDotsThree from '~icons/ph/dots-three-bold'
import IconNotePencil from '~icons/ph/note-pencil'
const actions = [
{ icon: IconNotePencil, onClick: () => {} },
{
type: 'menu' as const,
icon: IconDotsThree,
options: [
{ label: 'Inspect', onClick: () => {} },
{ label: 'Preview', onClick: () => {} },
{ label: 'Delete', onClick: () => {} }
]
}
]
</script>
<template>
<SDesc cols="2" gap="24">
<SDescItem span="1">
<SDescLabel :actions="actions">Full name</SDescLabel>
<SDescText>Margot …
```

feat(desc): add actions option

---

lib/components/SInputBase.vue
lib/components/SInputNumber.vue
lib/components/SInputText.vue
lib/components/SInputTextarea.vue
lib/styles/variables.css
stories/components/SInputText.01_Playground.story.vue

I'm not proud of my self but added `:warning` props to text, textarea, and number input components. Also refactored those to use base props exported from base input (there were just so many input to do it in one shot 😅 )

feat(input): add warning props to text, textarea, and number

---

docs/network-requests/http.md
lib/http/Http.ts
lib/support/Utils.ts

In some cases, we'd like to pass options to the stringify method when processing query parameters for HTTP requests.
For example, some servers accept array query parameters in the format `a=b&a=c&a=d`, while others require a different format like `a[0]=b&a[1]=c&a[2]=d`.
In such cases, we'd like to pass the `arrayFormat` option to the stringify method.

feat(http): support configuring stringify options

---

lib/composables/Lang.ts
lib/validation/Rule.ts

as they can be called without component instance and useLang won't work since it relies on provide/inject pattern

fix: directly use `html[lang]` in rules

---

lib/components/SState.vue
lib/styles/variables.css

In order to adhere the latest style. Basically transparent BG.

feat(style): add new bg color scheme and update pill and state style

---

stories/components/STable.01_Playground.story.vue

- ref #599
I'm not sure of the exact cause of the original issue.
But my guess is that the `computed()` call complicated the type inference process significantly—especially for the `cell` field, which is the return value of callback functions that are themselves the return value of a generic function (`computed<T>`). TypeScript loses track of the connection between the several `R` generic types in the `useTable` call and, therefore, throws an error.
By using `computed()` only at the lowest necessary level, we can simplify and make the type inference process work.

fix: make the `records` type inference in `useTable` call work

---

docs/components/control.md
lib/components/SControlPagination.vue
lib/components/SPagination.vue

There are some cases where we want to explicitly disable the pagination buttons (the "prev" and "next" buttons), such as when waiting for a network request to complete.
To handle this, add a `disabled` prop to `SPagination` and `SControlPagination`.

feat(pagination): add disabled prop to SPagination and SControlPagination

---

lib/components/STable.vue
lib/composables/Table.ts
stories/components/STable.01_Playground.story.vue

closes #630
doesn't support `%` as unit

feat(table): support specifying width in column options

---

lib/components/SActionMenu.vue

- ref #632
Added `:dropdownAlign` prop to control dropdown content position. Related to #632, but now I realized it would be also nice to be able to control this manually so adding this 👀

feat(action-menu): add dropdown align option

---

lib/components/SContent.vue
lib/styles/utilities.css
stories/components/SContent.01_Playground.story.vue

Refine `<SContent>` styling a bit.
1. New heading font sizes.
2. Increase max width to 720px.
- Many AI chat responses uses around 720-768px width. Since we use font size 14px, I went with 720px for now.
- Assuming that people are getting use to longer paragraph sizes.
3. Reduce paragraph gaps to 8px.
- The component is used mainly in places where we have fewer texts. Like only heading plus 1 paragraph. In this kind of case, 8px instead of 12px looks bit nicer.

feat(content): refine content styles
